
server:
  port: 8011
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://admin:123456@localhost:8761/eureka/
service-url:
     micorservice-admin: http://micorservice-admin

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' #暴露hystrix监控端点,被监控需要开启Actuator的hystrix.stream端点


