
server:
  port: 8082
spring:
  application:
    name: micorservice-admin
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://admin:123456@localhost:8761/eureka/